name: GitHub Actions
on:
  push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Init project
        run: |
          npm install
          make install
      - name: Run linter
        run: make lint